version: "3.9"

services:
  sessionapp-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sessionapp-api
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production